services:
  hass:
    container_name: hass
    image: "ghcr.io/home-assistant/home-assistant:2024.12.5"
    restart: always
    network_mode: host
    volumes:
      - "/opt/homeAssistant/data:/config"
      #- "/opt/homeAssistant/hacs/huawei_solar:/config/custom_components/huawei_solar"
      #- "/opt/homeAssistant/hacs/huawei_solar_pees/packages:/config/packages"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - TZ=Europe/Berlin
    labels:
      - com.centurylinklabs.watchtower.enable=true

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: always
    network_mode: host
    volumes:
      - "/opt/homeAssistant/matter/data:/data"
    environment:
      - TZ=Europe/Berlin
    labels:
      - com.centurylinklabs.watchtower.enable=true


  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    networks:
      - hass-net
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "./mosquitto-config:/mosquitto/config"
      - "/opt/mosquitto/data:/mosquitto/data"
      - "/opt/mosquitto/log:/mosquitto/log"
    environment:
      - TZ=Europe/Berlin
    labels:
      - com.centurylinklabs.watchtower.enable=true


networks:
    hass-net:
        driver: bridge
